//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPlaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TImageFile
    {
        public int EntryId { get; set; }
        public Nullable<int> placeId { get; set; }
        public string image { get; set; }
    
        public virtual TPlace TPlace { get; set; }
    }
}
