//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPlaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPlace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPlace()
        {
            this.TImageFiles = new HashSet<TImageFile>();
        }
    
        public int PlaceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string Significance { get; set; }
        public string State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TImageFile> TImageFiles { get; set; }
    }
}
